server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret}      # troque em produção
    access-exp-seconds: 3600              # 1h
    refresh-exp-seconds: 2592000

spring doc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger

spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST_PILOT}:${PG_PORT_PILOT}/${PG_DATABASE_PILOT}
    username: ${PG_USER_PILOT}
    password: ${PG_PASSWORD_PILOT}
    driver-class-name: org.postgresql.Driver   # ajuda o auto-detect
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none                           # não mexe no schema existente
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true                  # marca o estado atual do DB
    baseline-version: 1                        # primeira versão “marco”
    locations: classpath:db/migration          # pasta das futuras migrations

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # mostra parâmetros ? nos logs
    com.zaxxer.hikari: info
