server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST_PILOT}:${PG_PORT_PILOT}/${PG_DATABASE_PILOT}
    username: ${PG_USER_PILOT}
    password: ${PG_PASSWORD_PILOT}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
logging:
  level:
    org.hibernate.SQL: debug
